services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery_worker:
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    command: celery -A config beat -l INFO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: timescale/timescaledb:latest-pg18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homepage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d homepage"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
