# Generated by Django 6.0.2 on 2026-02-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotPrice",
            fields=[
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The hour the price applies to (HourDK)", primary_key=True, serialize=False
                    ),
                ),
                ("price_dkk", models.DecimalField(decimal_places=2, help_text="Price in DKK per MWh", max_digits=10)),
                ("price_eur", models.DecimalField(decimal_places=2, help_text="Price in EUR per MWh", max_digits=10)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [models.Index(fields=["-timestamp"], name="dashboard_s_timesta_a23076_idx")],
            },
        ),
    ]
