# Generated by Django 6.0.2 on 2026-02-27 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("CREATE EXTENSION IF NOT EXISTS timescaledb;"),
                ("SELECT create_hypertable('dashboard_spotprice', 'timestamp');"),
            ],
            reverse_sql="DROP TABLE dashboard_spotprice;",
        )
    ]
