# Generated by Django 6.0.4 on 2026-04-14 19:28
# Dangerous hypertable operations removed — managed=False models only

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_timescaledb_compression_and_hierarchical_aggregates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPriceDaily',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={'db_table': 'dashboard_spotprice_daily', 'ordering': ['-bucket'], 'managed': False},
        ),
        migrations.CreateModel(
            name='SpotPriceHourly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={'db_table': 'dashboard_spotprice_hourly', 'ordering': ['-bucket'], 'managed': False},
        ),
        migrations.CreateModel(
            name='SpotPriceMonthly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={'db_table': 'dashboard_spotprice_monthly', 'ordering': ['-bucket'], 'managed': False},
        ),
        migrations.CreateModel(
            name='SpotPriceYearly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={'db_table': 'dashboard_spotprice_yearly', 'ordering': ['-bucket'], 'managed': False},
        ),
    ]
