# Generated by Django 6.0.4 on 2026-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_timescaledb_compression_and_hierarchical_aggregates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPriceDaily',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dashboard_spotprice_daily',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPriceHourly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dashboard_spotprice_hourly',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPriceMonthly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dashboard_spotprice_monthly',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPriceYearly',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_area', models.CharField(max_length=3)),
                ('avg_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('avg_price_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('min_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_price_dkk', models.DecimalField(decimal_places=6, max_digits=12)),
                ('sample_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dashboard_spotprice_yearly',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='spotprice',
            name='dashboard_s_timesta_a23076_idx',
        ),
        migrations.AddField(
            model_name='spotprice',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spotprice',
            name='price_area',
            field=models.CharField(choices=[('DK1', 'DK1 (West Denmark)'), ('DK2', 'DK2 (East Denmark)')], default='DK1', help_text='Price area: DK1 (West) or DK2 (East)', max_length=3),
        ),
        migrations.AlterField(
            model_name='spotprice',
            name='timestamp',
            field=models.DateTimeField(help_text='UTC timestamp for this price interval'),
        ),
        migrations.AddConstraint(
            model_name='spotprice',
            constraint=models.UniqueConstraint(fields=('timestamp', 'price_area'), name='uq_spotprice_timestamp_area'),
        ),
    ]
