# Generated by Django 4.1.7 on 2023-03-10 14:17

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("content", markdownx.models.MarkdownxField()),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("summary", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
