# Generated by Django 6.0.4 on 2026-04-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field from title for existing posts, handling duplicates."""
    Post = apps.get_model("blog", "Post")
    seen: dict[str, bool] = {}
    for post in Post.objects.filter(slug="").order_by("id"):
        base_slug = slugify(post.title) or f"post-{post.id}"
        slug = base_slug
        counter = 1
        while slug in seen:
            slug = f"{base_slug}-{counter}"
            counter += 1
        seen[slug] = True
        post.slug = slug
        post.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        # Step 1: Add slug as non-unique with blank default
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, default=""),
            preserve_default=False,
        ),
        # Step 2: Populate slugs from titles before adding unique constraint
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Make slug unique now that all values are populated
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
