# Generated by Django 6.0.4 on 2026-04-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def ensure_slug_column_and_populate(apps, schema_editor):
    """
    Idempotent: ensure slug column exists (non-unique), populate empty slugs,
    handle partially-applied state from prior failed migration runs.
    """
    connection = schema_editor.connection

    # Check if slug column exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_name='blog_post' AND column_name='slug'
        """)
        slug_exists = cursor.fetchone()[0] > 0

    # Drop partial indexes if they exist (outside transaction since atomic=False)
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS blog_post_slug_key")
        cursor.execute("DROP INDEX IF EXISTS blog_post_slug_b95473f2_like")

    # Add slug column if missing
    if not slug_exists:
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE blog_post ADD COLUMN slug varchar(200) NOT NULL DEFAULT ''")
            cursor.execute("ALTER TABLE blog_post ALTER COLUMN slug DROP DEFAULT")

    # Populate empty slugs from titles
    Post = apps.get_model("blog", "Post")
    seen: dict[str, bool] = {}
    for post in Post.objects.filter(slug="").order_by("id"):
        base_slug = slugify(post.title) or f"post-{post.id}"
        slug = base_slug
        counter = 1
        while slug in seen:
            slug = f"{base_slug}-{counter}"
            counter += 1
        seen[slug] = True
        post.slug = slug
        post.save(update_fields=["slug"])


def create_slug_indexes(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE UNIQUE INDEX blog_post_slug_key ON blog_post (slug)")
        cursor.execute("CREATE INDEX blog_post_slug_b95473f2_like ON blog_post (slug varchar_pattern_ops)")


class Migration(migrations.Migration):
    atomic = False  # Required: index operations cannot run inside a transaction

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        # Step 1+2: Ensure column exists and populate slugs (fully idempotent)
        migrations.RunPython(
            ensure_slug_column_and_populate,
            migrations.RunPython.noop,
        ),
        # Step 3: Create indexes + sync Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_slug_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="post",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=200, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
