version: "3.9"

services:
  web:
    image: mkofoeddk/homepage:latest
    command: gunicorn --bind=0.0.0.0:5000 --workers=4 --access-logfile=- project.wsgi
    env_file:
      - .env
    working_dir: /homepage
    ports:
      - "80:5000"
    volumes:
      - static_volume:/homepage/staticfiles

  nginx:
    image: nginx:1.23
    restart: always
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  static_volume:
