version: "3.9"

services:
  web:
    image: mkofoeddk/homepage:latest
    command: gunicorn --bind=0.0.0.0:5000 --timeout=0 --workers=2 --access-logfile=- project.wsgi
    working_dir: /homepage
    volumes:
      - ../.:/homepage
      - static_volume:/homepage/staticfiles
      - media_volume:/homepage/media
    depends_on:
      - postgres
      - nginx

  nginx:
    image: jonasal/nginx-certbot:4.2-alpine
    restart: always
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - static_volume:/static
      - media_volume:/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/user_conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  static_volume:
  media_volume:
  nginx_secrets:
