server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name mkofoed.dk www.mkofoed.dk;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/mkofoed-cert/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/mkofoed-cert/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/mkofoed-cert/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location /static/ {
        autoindex on;
        alias /static/;
    }

    location /media/ {
        autoindex on;
        alias /media/;
    }

    # Redirect HTTP to HTTPS.
    if ($scheme != "https") {
        return 301 https://$server_name$request_uri;
    }

    location / {
        proxy_pass http://web:5000;
        proxy_set_header Host $host;
    }
}
