name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2
env:
  IMAGE_NAME: "homepage"

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build container image
        working-directory: ./ops
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to Docker Hub
        working-directory: ./ops
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Transfer repo to remote machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: .
          target: /homepage/

      - name: Copy env vars to .env file
        run: |
          echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" > app.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> app.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> app.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> app.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> app.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> app.env
          echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> app.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> app.env

      - name: Copy .env file to remote machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: app.env
          target: /homepage/ops/

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ''
          envs: IMAGE_NAME,GITHUB_SHA
          script: |
            # Log in to Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            cd /homepage/ops/
            mv app.env .env

            # Pull latest images and build containers
            docker compose -f docker-compose.production.yml up -d --build
