name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

    - name: Build and push
      uses: docker/build-push-action@48aba3b46827194d2ce6b1e7a4de561be3fbe4c2 # v6
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: mkofoeddk/homepage-web:latest
        cache-from: type=registry,ref=mkofoeddk/homepage-web:buildcache
        cache-to: type=registry,ref=mkofoeddk/homepage-web:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@50ac135b5cc24900da4c88ae0d2a71c2cca01c30 # v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/homepage
          printf '%s' "${{ secrets.ENV_FILE }}" > .env
          ./deploy.sh
